In [3]:
from pathlib import Path
import pandas as pd

parquet_path = Path("../data/task_a/task_a_test.parquet")

df = pd.read_parquet(parquet_path)
print(f"Shape: {df.shape}")
df.head()

Shape: (500000, 2)

   ID                                               code
0   0  (H, W) = map(int, input().split())\nA = [list(...
2   2  n = int(input())\nt = list(map(int, input().sp...
5   5  import sys\n\nclass LazySegmentTree:\n    def ...
6   6  n = int(input())\ns = input()\ntup = []\nfor i...
7   7  import sys\ninput = sys.stdin.readline\nfrom m...

In [4]:
sub_df = pd.read_csv("../artifacts/subtask_a/submission.csv")
sub_df

            id  label
0            0      0
1            1      0
2            2      1
3            3      0
4            4      0
...        ...    ...
499995  499995      0
499996  499996      1
499997  499997      1
499998  499998      1
499999  499999      1

[500000 rows x 2 columns]